config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn %default
    ikelifetime=60m
    keylife=20m
    rekeymargin=3m
    keyingtries=1
    keyexchange=ikev2
    authby=secret

conn aws-fortigate
    left=%defaultroute
    leftid=<REMOTE_BRANCH_PUBLIC_IP>
    leftsubnet=192.168.100.0/24
    right=<REDACTED_PUBLIC_IP>
    rightid=<REDACTED_PUBLIC_IP>
    rightsubnet=10.10.18.0/24
    ike=aes256-sha256-modp1024!
    esp=aes256-sha256!
    auto=start
